[build]
  # 构建命令：安装依赖
  command = "pip install -r requirements.txt"
  
  # 发布根目录 (包含 templates/)
  publish = "."
  
         # 环境变量
        [build.environment]
          PYTHON_VERSION = "3.11"
          PIP_ROOT_USER_ACTION = "ignore"
    DATABASE_TYPE = "turso"
    # 在Netlify控制台中设置以下环境变量：
    # TURSO_URL = "your-turso-database-url"
    # TURSO_AUTH_TOKEN = "your-turso-auth-token"
    # SECRET_KEY = "your-secret-key"

# 利用原生 Flask + Jinja2 应用
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  # 函数目录
  directory = "netlify/functions"
