[build]
  # 构建命令
  command = "pip install -r requirements.txt"
  
  # 发布目录
  publish = "."
  
  # 环境变量
  [build.environment]
    PYTHON_VERSION = "3.11"
    DATABASE_TYPE = "turso"
    # 在Netlify控制台中设置以下环境变量：
    # TURSO_URL = "your-turso-database-url"
    # TURSO_AUTH_TOKEN = "your-turso-auth-token"
    # SECRET_KEY = "your-secret-key"

# 重定向规则 - 将所有请求转发到Flask应用
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

# 函数配置
[functions]
  # 函数目录
  directory = "netlify/functions"
